version: '3.5'
services:
  tomcat:
    image: bitnami/tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - ./:/bitnami
      - ./src/main/webapp/META-INF/context.xml:/opt/bitnami/tomcat/conf/context.xml
    environment:
      - TOMCAT_USERNAME=admin
      - TOMCAT_PASSWORD=admin
      - TOMCAT_ALLOW_REMOTE_MANAGEMENT=1
    networks:
      - proxynet

  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coderslab
      MYSQL_DATABASE: workshop
      MYSQL_USER: root
      MYSQL_PASSWORD: coderslab
    ports:
      - 3306:3306
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet