version: '3.3'
services:
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coderslab
      MYSQL_DATABASE: workshop2
      MYSQL_USER: root
      MYSQL_PASSWORD: coderslab
    ports:
      - 3306:3306
